#!/usr/bin/env bash

function createFinanceOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/finance.treasurychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/finance.treasurychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname FinanceCA --tls.certfiles "${PWD}/organizations/fabric-ca/finance/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-FinanceCA.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-FinanceCA.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-FinanceCA.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-FinanceCA.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy Finance's CA cert to Finance's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/finance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/msp/tlscacerts/ca.crt"

  # Copy Finance's CA cert to Finance's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/finance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/tlsca/tlsca.finance.treasurychain.com-cert.pem"

  # Copy Finance's CA cert to Finance's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/finance/ca-cert.pem" "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/ca/ca.finance.treasurychain.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname FinanceCA --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/finance/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname FinanceCA --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/finance/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname FinanceCA --id.name financeadmin --id.secret financeadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/finance/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname FinanceCA -M "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/finance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname FinanceCA -M "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/tls" --enrollment.profile tls --csr.hosts peer0.finance.treasurychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/finance/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/peers/peer0.finance.treasurychain.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname FinanceCA -M "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/users/User1@finance.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/finance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/users/User1@finance.treasurychain.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://financeadmin:financeadminpw@localhost:7054 --caname FinanceCA -M "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/users/Admin@finance.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/finance/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/finance.treasurychain.com/users/Admin@finance.treasurychain.com/msp/config.yaml"
}

function createTrusteeOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/trustee.treasurychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname TrusteeCA --tls.certfiles "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-TrusteeCA.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-TrusteeCA.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-TrusteeCA.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-TrusteeCA.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy Trustee's CA cert to Trustee's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem" "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/msp/tlscacerts/ca.crt"

  # Copy Trustee's CA cert to Trustee's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem" "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/tlsca/tlsca.trustee.treasurychain.com-cert.pem"

  # Copy Trustee's CA cert to Trustee's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem" "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/ca/ca.trustee.treasurychain.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname TrusteeCA --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname TrusteeCA --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname TrusteeCA --id.name trusteeadmin --id.secret trusteeadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname TrusteeCA -M "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname TrusteeCA -M "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/tls" --enrollment.profile tls --csr.hosts peer0.trustee.treasurychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/peers/peer0.trustee.treasurychain.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname TrusteeCA -M "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/users/User1@trustee.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/users/User1@trustee.treasurychain.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://trusteeadmin:trusteeadminpw@localhost:8054 --caname TrusteeCA -M "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/users/Admin@trustee.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/trustee/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/trustee.treasurychain.com/users/Admin@trustee.treasurychain.com/msp/config.yaml"
}

function createOperationsOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/operations.treasurychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/operations.treasurychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname OperationsCA --tls.certfiles "${PWD}/organizations/fabric-ca/operations/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-OperationsCA.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-OperationsCA.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-OperationsCA.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-OperationsCA.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy Operations' CA cert to Operations' /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/operations/ca-cert.pem" "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/msp/tlscacerts/ca.crt"

  # Copy Operations' CA cert to Operations' /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/operations/ca-cert.pem" "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/tlsca/tlsca.operations.treasurychain.com-cert.pem"

  # Copy Operations' CA cert to Operations' /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/operations/ca-cert.pem" "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/ca/ca.operations.treasurychain.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname OperationsCA --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/operations/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname OperationsCA --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/operations/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname OperationsCA --id.name operationsadmin --id.secret operationsadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/operations/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9054 --caname OperationsCA -M "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/operations/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9054 --caname OperationsCA -M "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/tls" --enrollment.profile tls --csr.hosts peer0.operations.treasurychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/operations/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/peers/peer0.operations.treasurychain.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:9054 --caname OperationsCA -M "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/users/User1@operations.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/operations/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/users/User1@operations.treasurychain.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://operationsadmin:operationsadminpw@localhost:9054 --caname OperationsCA -M "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/users/Admin@operations.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/operations/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/operations.treasurychain.com/users/Admin@operations.treasurychain.com/msp/config.yaml"
}

function createAuditOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/audit.treasurychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/audit.treasurychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname AuditCA --tls.certfiles "${PWD}/organizations/fabric-ca/audit/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-AuditCA.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-AuditCA.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-AuditCA.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-AuditCA.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy Audit's CA cert to Audit's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/audit/ca-cert.pem" "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/msp/tlscacerts/ca.crt"

  # Copy Audit's CA cert to Audit's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/audit/ca-cert.pem" "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/tlsca/tlsca.audit.treasurychain.com-cert.pem"

  # Copy Audit's CA cert to Audit's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/audit/ca-cert.pem" "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/ca/ca.audit.treasurychain.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname AuditCA --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/audit/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname AuditCA --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/audit/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname AuditCA --id.name auditadmin --id.secret auditadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/audit/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname AuditCA -M "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/audit/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname AuditCA -M "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/tls" --enrollment.profile tls --csr.hosts peer0.audit.treasurychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/audit/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/peers/peer0.audit.treasurychain.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname AuditCA -M "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/users/User1@audit.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/audit/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/users/User1@audit.treasurychain.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://auditadmin:auditadminpw@localhost:10054 --caname AuditCA -M "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/users/Admin@audit.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/audit/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/audit.treasurychain.com/users/Admin@audit.treasurychain.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/orderer.treasurychain.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname OrdererCA --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-OrdererCA.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-OrdererCA.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-OrdererCA.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-OrdererCA.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/msp/tlscacerts/tlsca.orderer.treasurychain.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/tlsca/tlsca.orderer.treasurychain.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname OrdererCA --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer MSP"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:11054 --caname OrdererCA -M "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/msp/config.yaml"

  infoln "Generating the orderer TLS certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:11054 --caname OrdererCA -M "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/tls" --enrollment.profile tls --csr.hosts orderer.orderer.treasurychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/orderers/orderer.orderer.treasurychain.com/msp/tlscacerts/tlsca.orderer.treasurychain.com-cert.pem"

  # Register and generate artifacts for the orderer admin
  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname OrdererCA --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:11054 --caname OrdererCA -M "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/users/Admin@orderer.treasurychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/orderer.treasurychain.com/users/Admin@orderer.treasurychain.com/msp/config.yaml"
}